// Older protoc compilers don't understand edition yet.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file a2a.proto (package a2a.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentCard, CancelTaskRequest, CreateTaskPushNotificationConfigRequest, DeleteTaskPushNotificationConfigRequest, GetExtendedAgentCardRequest, GetTaskPushNotificationConfigRequest, GetTaskRequest, ListTaskPushNotificationConfigRequest, ListTaskPushNotificationConfigResponse, ListTasksRequest, ListTasksResponse, SendMessageRequest, SendMessageResponse, StreamResponse, SubscribeToTaskRequest, Task, TaskPushNotificationConfig } from "./a2a_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * A2AService defines the operations of the A2A protocol.
 *
 * @generated from service a2a.v1.A2AService
 */
export const A2AService = {
  typeName: "a2a.v1.A2AService",
  methods: {
    /**
     * Send a message to the agent.
     *
     * @generated from rpc a2a.v1.A2AService.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: SendMessageRequest,
      O: SendMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SendStreamingMessage is a streaming version of SendMessage.
     *
     * @generated from rpc a2a.v1.A2AService.SendStreamingMessage
     */
    sendStreamingMessage: {
      name: "SendStreamingMessage",
      I: SendMessageRequest,
      O: StreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Get the current state of a task from the agent.
     *
     * @generated from rpc a2a.v1.A2AService.GetTask
     */
    getTask: {
      name: "GetTask",
      I: GetTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * List tasks with optional filtering and pagination.
     *
     * @generated from rpc a2a.v1.A2AService.ListTasks
     */
    listTasks: {
      name: "ListTasks",
      I: ListTasksRequest,
      O: ListTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Cancel a task.
     *
     * @generated from rpc a2a.v1.A2AService.CancelTask
     */
    cancelTask: {
      name: "CancelTask",
      I: CancelTaskRequest,
      O: Task,
      kind: MethodKind.Unary,
    },
    /**
     * SubscribeToTask allows subscribing to task updates for tasks not in
     * terminal state. Returns UnsupportedOperationError if task is in terminal
     * state (completed, failed, canceled, rejected).
     *
     * @generated from rpc a2a.v1.A2AService.SubscribeToTask
     */
    subscribeToTask: {
      name: "SubscribeToTask",
      I: SubscribeToTaskRequest,
      O: StreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Create a push notification config for a task.
     *
     * @generated from rpc a2a.v1.A2AService.CreateTaskPushNotificationConfig
     */
    createTaskPushNotificationConfig: {
      name: "CreateTaskPushNotificationConfig",
      I: CreateTaskPushNotificationConfigRequest,
      O: TaskPushNotificationConfig,
      kind: MethodKind.Unary,
    },
    /**
     * Get a push notification config for a task.
     *
     * @generated from rpc a2a.v1.A2AService.GetTaskPushNotificationConfig
     */
    getTaskPushNotificationConfig: {
      name: "GetTaskPushNotificationConfig",
      I: GetTaskPushNotificationConfigRequest,
      O: TaskPushNotificationConfig,
      kind: MethodKind.Unary,
    },
    /**
     * Get a list of push notifications configured for a task.
     *
     * @generated from rpc a2a.v1.A2AService.ListTaskPushNotificationConfig
     */
    listTaskPushNotificationConfig: {
      name: "ListTaskPushNotificationConfig",
      I: ListTaskPushNotificationConfigRequest,
      O: ListTaskPushNotificationConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetExtendedAgentCard returns the extended agent card for authenticated
     * agents.
     *
     * @generated from rpc a2a.v1.A2AService.GetExtendedAgentCard
     */
    getExtendedAgentCard: {
      name: "GetExtendedAgentCard",
      I: GetExtendedAgentCardRequest,
      O: AgentCard,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a push notification config for a task.
     *
     * @generated from rpc a2a.v1.A2AService.DeleteTaskPushNotificationConfig
     */
    deleteTaskPushNotificationConfig: {
      name: "DeleteTaskPushNotificationConfig",
      I: DeleteTaskPushNotificationConfigRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

