/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/pages/playground/components/AppLayout/AppLayout.vue')['default']
    AudioRecorder: typeof import('./src/pages/playground/components/ContentInput/AudioRecorder.vue')['default']
    ContentInput: typeof import('./src/pages/playground/components/ContentInput/ContentInput.vue')['default']
    DataPart: typeof import('./src/pages/playground/components/MessageParts/DataPart.vue')['default']
    DetailsDrawer: typeof import('./src/pages/playground/components/DetailsDrawer.vue')['default']
    FilePart: typeof import('./src/pages/playground/components/MessageParts/FilePart.vue')['default']
    FileUploader: typeof import('./src/pages/playground/components/ContentInput/FileUploader.vue')['default']
    MessageBubble: typeof import('./src/pages/playground/components/MessageBubble.vue')['default']
    PendingFunctionResponseBlock: typeof import('./src/pages/playground/components/PendingFunctionResponseBlock.vue')['default']
    RichTextInput: typeof import('./src/pages/playground/components/ContentInput/RichTextInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskStatusWidget: typeof import('./src/pages/playground/components/TaskStatusWidget.vue')['default']
    TextPart: typeof import('./src/pages/playground/components/MessageParts/TextPart.vue')['default']
  }
}
